import React, { useState } from 'react';
import {
  X,
  Terminal,
  Cpu,
  FileCode,
  Download,
  Upload,
  CheckCircle2,
  Layers,
  Database,
  Monitor,
  HardDrive,
  FileSpreadsheet,
  ShieldCheck,
  Zap,
  AlertCircle
} from 'lucide-react';
import { Language, NetworkDevice } from '../types';
import { getTranslation } from '../data/i18n';

interface PcRemoteManagerModalProps {
  isOpen: boolean;
  onClose: () => void;
  lang: Language;
  onImportDevices: (importedDevices: Partial<NetworkDevice>[]) => void;
}

export const PcRemoteManagerModal: React.FC<PcRemoteManagerModalProps> = ({
  isOpen,
  onClose,
  lang,
  onImportDevices
}) => {
  if (!isOpen) return null;

  const t = getTranslation(lang);

  const [activeTab, setActiveTab] = useState<'overview' | 'dependencies' | 'importer' | 'config'>('overview');
  const [importedJson, setImportedJson] = useState<string>('');
  const [importStatus, setImportStatus] = useState<string | null>(null);
  const [importError, setImportError] = useState<string | null>(null);

  // Pre-configured .NET 8.0 deps manifest details from user JSON
  const rawDepsJson = {
    runtimeTarget: {
      name: '.NETCoreApp,Version=v8.0',
      signature: ''
    },
    compilationOptions: {},
    targets: {
      '.NETCoreApp,Version=v8.0': {
        'PcRemoteManager/1.0.0': {
          dependencies: {
            ClosedXML: '0.102.3',
            'System.Management': '8.0.0'
          },
          runtime: {
            'PcRemoteManager.dll': {}
          }
        },
        'ClosedXML/0.102.3': {
          dependencies: {
            'DocumentFormat.OpenXml': '2.16.0',
            ExcelNumberFormat: '1.1.0',
            'SixLabors.Fonts': '1.0.0',
            XLParser: '1.5.2'
          },
          runtime: {
            'lib/netstandard2.1/ClosedXML.dll': {
              assemblyVersion: '0.102.3.0',
              fileVersion: '0.102.3.0'
            }
          }
        },
        'DocumentFormat.OpenXml/2.16.0': {
          runtime: {
            'lib/netstandard2.0/DocumentFormat.OpenXml.dll': {
              assemblyVersion: '2.16.0.0',
              fileVersion: '2.16.0.0'
            }
          }
        },
        'ExcelNumberFormat/1.1.0': {
          runtime: {
            'lib/netstandard2.0/ExcelNumberFormat.dll': {
              assemblyVersion: '1.1.0.0',
              fileVersion: '1.1.0.0'
            }
          }
        },
        'SixLabors.Fonts/1.0.0': {
          runtime: {
            'lib/netcoreapp3.1/SixLabors.Fonts.dll': {
              assemblyVersion: '1.0.0.0',
              fileVersion: '1.0.0.0'
            }
          }
        },
        'System.Management/8.0.0': {
          runtime: {
            'lib/net8.0/System.Management.dll': {
              assemblyVersion: '8.0.0.0',
              fileVersion: '8.0.23.53103'
            }
          },
          runtimeTargets: {
            'runtimes/win/lib/net8.0/System.Management.dll': {
              rid: 'win',
              assetType: 'runtime',
              assemblyVersion: '8.0.0.0',
              fileVersion: '8.0.23.53103'
            }
          }
        },
        'XLParser/1.5.2': {
          dependencies: {
            'Irony.NetCore': '1.0.11'
          },
          runtime: {
            'lib/netstandard1.6/XLParser.dll': {
              assemblyVersion: '1.5.2.0',
              fileVersion: '1.5.2.0'
            }
          }
        }
      }
    }
  };

  const rawRuntimeConfigJson = {
    runtimeOptions: {
      tfm: 'net8.0',
      frameworks: [
        {
          name: 'Microsoft.NETCore.App',
          version: '8.0.0'
        },
        {
          name: 'Microsoft.WindowsDesktop.App',
          version: '8.0.0'
        }
      ],
      configProperties: {
        CSWINRT_USE_WINDOWS_UI_XAML_PROJECTIONS: false
      }
    }
  };

  // Sample PcRemoteManager Agent Inventory payload generated by System.Management 8.0.0
  // Paste your own JSON scan data from the PcRemoteManager agent above

  const handleDownloadDeps = () => {
    const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(rawDepsJson, null, 2));
    const dlAnchor = document.createElement('a');
    dlAnchor.setAttribute('href', dataStr);
    dlAnchor.setAttribute('download', 'PcRemoteManager.deps.json');
    document.body.appendChild(dlAnchor);
    dlAnchor.click();
    dlAnchor.remove();
  };

  const handleDownloadRuntimeConfig = () => {
    const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(rawRuntimeConfigJson, null, 2));
    const dlAnchor = document.createElement('a');
    dlAnchor.setAttribute('href', dataStr);
    dlAnchor.setAttribute('download', 'PcRemoteManager.runtimeconfig.json');
    document.body.appendChild(dlAnchor);
    dlAnchor.click();
    dlAnchor.remove();
  };

  const handleExecuteImportSample = () => {
    setImportError(null);
    setImportStatus('Paste your PcRemoteManager JSON scan data above, then click Process & Add to Inventory.');
    setTimeout(() => setImportStatus(null), 5000);
  };

  const handleCustomImport = () => {
    setImportError(null);
    try {
      if (!importedJson.trim()) {
        setImportError('Please paste JSON scan data from PcRemoteManager agent first.');
        return;
      }
      const parsed = JSON.parse(importedJson);
      const items = Array.isArray(parsed) ? parsed : [parsed];
      onImportDevices(items);
      setImportStatus(`${items.length} device(s) imported successfully.`);
      setImportedJson('');
      setTimeout(() => setImportStatus(null), 4000);
    } catch (e) {
      setImportError('Invalid JSON format. Please ensure valid JSON scan data.');
    }
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/70 flex items-center justify-center p-3 sm:p-4 backdrop-blur-xs">
      <div className="bg-[#1A1C23] text-white rounded border border-[#2D303E] shadow-2xl w-full max-w-4xl overflow-hidden font-sans flex flex-col max-h-[90vh]">
        {/* Header */}
        <div className="p-4 bg-[#14161D] border-b border-[#2D303E] flex items-center justify-between shrink-0">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-purple-600/20 text-purple-400 rounded border border-purple-500/30">
              <Terminal className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-sm font-bold font-mono text-white flex items-center gap-2">
                {t.agentModalTitle}
                <span className="text-[10px] px-2 py-0.5 bg-purple-500/20 text-purple-300 border border-purple-500/40 rounded-full font-mono">
                  .NET 8.0 Desktop App
                </span>
              </h2>
              <p className="text-[11px] text-gray-400 font-mono mt-0.5">{t.agentSubtitle}</p>
            </div>
          </div>
          <button onClick={onClose} className="text-gray-400 hover:text-white cursor-pointer p-1">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Tab Selection */}
        <div className="bg-[#14161D] px-4 border-b border-[#2D303E] flex gap-2 text-xs font-mono shrink-0">
          <button
            onClick={() => setActiveTab('overview')}
            className={`py-2.5 px-3 border-b-2 font-bold cursor-pointer transition-colors flex items-center gap-1.5 ${
              activeTab === 'overview'
                ? 'border-purple-500 text-purple-400'
                : 'border-transparent text-gray-400 hover:text-gray-200'
            }`}
          >
            <Cpu className="w-3.5 h-3.5" />
            Runtime Overview
          </button>
          <button
            onClick={() => setActiveTab('dependencies')}
            className={`py-2.5 px-3 border-b-2 font-bold cursor-pointer transition-colors flex items-center gap-1.5 ${
              activeTab === 'dependencies'
                ? 'border-purple-500 text-purple-400'
                : 'border-transparent text-gray-400 hover:text-gray-200'
            }`}
          >
            <Layers className="w-3.5 h-3.5" />
            Assemblies (.deps.json)
          </button>
          <button
            onClick={() => setActiveTab('importer')}
            className={`py-2.5 px-3 border-b-2 font-bold cursor-pointer transition-colors flex items-center gap-1.5 ${
              activeTab === 'importer'
                ? 'border-purple-500 text-purple-400'
                : 'border-transparent text-gray-400 hover:text-gray-200'
            }`}
          >
            <Upload className="w-3.5 h-3.5" />
            JSON Importer
          </button>
          <button
            onClick={() => setActiveTab('config')}
            className={`py-2.5 px-3 border-b-2 font-bold cursor-pointer transition-colors flex items-center gap-1.5 ${
              activeTab === 'config'
                ? 'border-purple-500 text-purple-400'
                : 'border-transparent text-gray-400 hover:text-gray-200'
            }`}
          >
            <FileCode className="w-3.5 h-3.5" />
            Configs & Export
          </button>
        </div>

        {/* Tab Body */}
        <div className="p-4 overflow-y-auto flex-1 font-mono text-xs space-y-4">
          {activeTab === 'overview' && (
            <div className="space-y-4">
              {/* Top KPI Cards */}
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                <div className="p-3 bg-[#222530] rounded border border-[#2D303E]">
                  <span className="text-[10px] text-gray-400 uppercase font-bold block mb-1">Target Framework</span>
                  <div className="text-sm font-bold text-purple-400 flex items-center gap-1.5">
                    <Cpu className="w-4 h-4" />
                    .NETCoreApp v8.0
                  </div>
                  <span className="text-[10px] text-gray-500 block mt-1">Microsoft.WindowsDesktop.App 8.0.0</span>
                </div>

                <div className="p-3 bg-[#222530] rounded border border-[#2D303E]">
                  <span className="text-[10px] text-gray-400 uppercase font-bold block mb-1">WMI Query Engine</span>
                  <div className="text-sm font-bold text-blue-400 flex items-center gap-1.5">
                    <Database className="w-4 h-4" />
                    System.Management 8.0.0
                  </div>
                  <span className="text-[10px] text-gray-500 block mt-1">WinRM / WMI Hardware Diagnostics</span>
                </div>

                <div className="p-3 bg-[#222530] rounded border border-[#2D303E]">
                  <span className="text-[10px] text-gray-400 uppercase font-bold block mb-1">Spreadsheet Generator</span>
                  <div className="text-sm font-bold text-emerald-400 flex items-center gap-1.5">
                    <FileSpreadsheet className="w-4 h-4" />
                    ClosedXML v0.102.3
                  </div>
                  <span className="text-[10px] text-gray-500 block mt-1">OpenXml 2.16.0 + XLParser 1.5.2</span>
                </div>
              </div>

              {/* Module Integration Card */}
              <div className="p-4 bg-[#14161D] rounded border border-[#2D303E] space-y-3">
                <h3 className="text-xs font-bold text-gray-200 uppercase tracking-wider flex items-center gap-2">
                  <ShieldCheck className="w-4 h-4 text-purple-400" />
                  PcRemoteManager Active Agent Capabilities
                </h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-[11px] text-gray-300">
                  <div className="p-2.5 bg-[#1C1F2B] rounded border border-[#2D303E] space-y-1">
                    <div className="font-bold text-purple-300">Remote PC Hardware Telemetry</div>
                    <p className="text-gray-400 text-[10px]">
                      Queries CPU Cores, RAM capacity, GPU models, Motherboard Serial Numbers, and NVMe SSD disk health across <code className="text-blue-300">10.10.0.0/24</code> via WMI.
                    </p>
                  </div>

                  <div className="p-2.5 bg-[#1C1F2B] rounded border border-[#2D303E] space-y-1">
                    <div className="font-bold text-emerald-300">Automated ClosedXML Excel Audits</div>
                    <p className="text-gray-400 text-[10px]">
                      Generates native OpenXML spreadsheets (.xlsx) with formatting powered by <code className="text-emerald-300">SixLabors.Fonts 1.0.0</code> and <code className="text-emerald-300">ExcelNumberFormat 1.1.0</code>.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          )}

          {activeTab === 'dependencies' && (
            <div className="space-y-3">
              <div className="flex justify-between items-center">
                <h3 className="text-xs font-bold text-gray-200 uppercase">
                  NuGet Packages & Runtime Assembly Tree
                </h3>
                <span className="text-[10px] text-purple-400 font-mono">
                  Target: .NETCoreApp,Version=v8.0
                </span>
              </div>

              <div className="bg-[#14161D] p-3 rounded border border-[#2D303E] font-mono text-[11px] space-y-2 overflow-x-auto">
                <div className="text-purple-300 font-bold">📦 PcRemoteManager v1.0.0 (.NET 8.0 Project)</div>
                <div className="pl-4 space-y-1.5 border-l border-purple-500/30 text-gray-300">
                  <div className="flex items-center gap-2">
                    <span className="text-blue-400 font-bold">├── System.Management (8.0.0)</span>
                    <span className="text-[9px] px-1.5 py-0.2 bg-blue-900/40 text-blue-300 rounded">
                      runtimes/win/lib/net8.0/System.Management.dll
                    </span>
                  </div>

                  <div className="flex items-center gap-2">
                    <span className="text-emerald-400 font-bold">└── ClosedXML (0.102.3)</span>
                    <span className="text-[9px] px-1.5 py-0.2 bg-emerald-900/40 text-emerald-300 rounded">
                      lib/netstandard2.1/ClosedXML.dll
                    </span>
                  </div>

                  <div className="pl-6 space-y-1 text-gray-400 border-l border-gray-700 text-[10px]">
                    <div>├── DocumentFormat.OpenXml (2.16.0)</div>
                    <div>├── ExcelNumberFormat (1.1.0)</div>
                    <div>├── SixLabors.Fonts (1.0.0)</div>
                    <div>└── XLParser (1.5.2)</div>
                    <div className="pl-4 text-gray-500">└── Irony.NetCore (1.0.11)</div>
                  </div>
                </div>
              </div>
            </div>
          )}

          {activeTab === 'importer' && (
            <div className="space-y-3">
              <div className="flex justify-between items-center">
                <h3 className="text-xs font-bold text-gray-200 uppercase">
                  Import Scan JSON Payload from PcRemoteManager
                </h3>
                <button
                  onClick={handleExecuteImportSample}
                  className="px-2.5 py-1 bg-gray-600 hover:bg-gray-500 text-white font-bold rounded flex items-center gap-1 cursor-pointer transition-colors"
                >
                  <Zap className="w-3.5 h-3.5" />
                  How to Import
                </button>
              </div>

              {importStatus && (
                <div className="p-2.5 bg-emerald-900/40 border border-emerald-500/50 rounded text-emerald-300 text-[11px] font-bold flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4" />
                  {importStatus}
                </div>
              )}

              {importError && (
                <div className="p-2.5 bg-red-900/40 border border-red-500/50 rounded text-red-300 text-[11px] font-bold flex items-center gap-2">
                  <AlertCircle className="w-4 h-4" />
                  {importError}
                </div>
              )}

              <textarea
                rows={8}
                value={importedJson}
                onChange={(e) => setImportedJson(e.target.value)}
                placeholder={t.pasteJsonPlaceholder}
                className="w-full p-3 bg-[#14161D] border border-[#2D303E] rounded text-gray-200 font-mono text-[11px] focus:outline-none focus:border-purple-500"
              />

              <div className="flex justify-end gap-2">
                <button
                  onClick={handleCustomImport}
                  className="px-4 py-2 bg-purple-600 hover:bg-purple-700 text-white font-bold rounded cursor-pointer transition-colors flex items-center gap-1.5"
                >
                  <Upload className="w-3.5 h-3.5" />
                  Process & Add to Inventory
                </button>
              </div>
            </div>
          )}

          {activeTab === 'config' && (
            <div className="space-y-3">
              <h3 className="text-xs font-bold text-gray-200 uppercase">
                Export Application Metadata & Runtime Configurations
              </h3>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div className="p-3 bg-[#14161D] rounded border border-[#2D303E] space-y-2">
                  <div className="font-bold text-purple-400 text-[11px] flex items-center gap-1.5">
                    <FileCode className="w-4 h-4" />
                    PcRemoteManager.deps.json
                  </div>
                  <p className="text-[10px] text-gray-400">
                    Contains assembly target specifications for .NET 8.0, System.Management 8.0.0, and ClosedXML 0.102.3.
                  </p>
                  <button
                    onClick={handleDownloadDeps}
                    className="w-full py-1.5 bg-purple-600/30 hover:bg-purple-600/50 text-purple-200 border border-purple-500/40 rounded font-bold cursor-pointer flex items-center justify-center gap-1.5 transition-colors"
                  >
                    <Download className="w-3.5 h-3.5" />
                    Download .deps.json
                  </button>
                </div>

                <div className="p-3 bg-[#14161D] rounded border border-[#2D303E] space-y-2">
                  <div className="font-bold text-blue-400 text-[11px] flex items-center gap-1.5">
                    <FileCode className="w-4 h-4" />
                    PcRemoteManager.runtimeconfig.json
                  </div>
                  <p className="text-[10px] text-gray-400">
                    Defines .NET 8.0 desktop runtime framework specs (Microsoft.NETCore.App & Microsoft.WindowsDesktop.App).
                  </p>
                  <button
                    onClick={handleDownloadRuntimeConfig}
                    className="w-full py-1.5 bg-blue-600/30 hover:bg-blue-600/50 text-blue-200 border border-blue-500/40 rounded font-bold cursor-pointer flex items-center justify-center gap-1.5 transition-colors"
                  >
                    <Download className="w-3.5 h-3.5" />
                    Download .runtimeconfig.json
                  </button>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="p-3 bg-[#14161D] border-t border-[#2D303E] flex justify-between items-center text-[10px] text-gray-400 shrink-0 font-mono">
          <div>PcRemoteManager v1.0.0 (.NET 8.0 Desktop Agent Engine)</div>
          <button
            onClick={onClose}
            className="px-3 py-1 bg-gray-800 hover:bg-gray-700 text-gray-200 rounded font-bold cursor-pointer"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
